// Params
const SET_NUMBER_OF_EXERCISES = "SET_NUMBER_OF_EXERCISES"
const SET_EXERCISE_TIME = "SET_EXERCISE_TIME"
const SET_REST_TIME = "SET_REST_TIME"
const SET_NUMBER_OF_ROUNDS = "SET_NUMBER_OF_ROUNDS"
const CLEAR_PARAMS = "CLEAR_PARAMS"
const SET_EXERCISES = "SET_EXERCISES"
const SET_EXERCISE_ROUNDS = "SET_EXERCISE_ROUNDS"
const INCLUDE_DUMBBELLS = "INCLUDE_DUMBBELLS"
const EXCLUDE_DUMBBELLS = "EXCLUDE_DUMBBELLS"

// Is Active
const IS_ACTIVE_TRUE = "IS_ACTIVE_TRUE"
const IS_ACTIVE_FALSE = "IS_ACTIVE_FALSE"

// Success Gif Message
const SET_SUCCESS_GIF = "SET_SUCCESS_GIF"

export {
    // Params
    SET_NUMBER_OF_EXERCISES,
    SET_EXERCISE_TIME,
    SET_REST_TIME,
    SET_NUMBER_OF_ROUNDS,
    CLEAR_PARAMS,
    SET_EXERCISES,
    SET_EXERCISE_ROUNDS,
    INCLUDE_DUMBBELLS,
    EXCLUDE_DUMBBELLS,

    // Is Active
    IS_ACTIVE_TRUE,
    IS_ACTIVE_FALSE,

    // Success Gif Message
    SET_SUCCESS_GIF
}