// Params
const SET_NUMBER_OF_EXERCISES = "SET_NUMBER_OF_EXERCISES"
const SET_EXERCISE_TIME = "SET_EXERCISE_TIME"
const SET_REST_TIME = "SET_REST_TIME"
const SET_NUMBER_OF_ROUNDS = "SET_NUMBER_OF_ROUNDS"
const CLEAR_PARAMS = "CLEAR_PARAMS"
const SET_EXERCISES = "SET_EXERCISES"
const SET_EXERCISE_ROUNDS = "SET_EXERCISE_ROUNDS"
const INCLUDE_DUMBBELLS = "INCLUDE_DUMBBELLS"
const EXCLUDE_DUMBBELLS = "EXCLUDE_DUMBBELLS"

// Is Active
const IS_ACTIVE_TRUE = "IS_ACTIVE_TRUE"
const IS_ACTIVE_FALSE = "IS_ACTIVE_FALSE"

// Success Gif Message
const SET_SUCCESS_GIF = "SET_SUCCESS_GIF"

// Selected Styles
const CLEAR_SELECTED_STYLES = "CLEAR_SELECTED_STYLES"

const SET_ONE_EX = "SET_ONE_EX"
const SET_TWO_EX = "SET_TWO_EX"
const SET_THREE_EX = "SET_THREE_EX"
const SET_FOUR_EX = "SET_FOUR_EX"
const SET_FIVE_EX = "SET_FIVE_EX"
const SET_SIX_EX = "SET_SIX_EX"
const SET_SEVEN_EX = "SET_SEVEN_EX"
const SET_EIGHT_EX = "SET_EIGHT_EX"
const SET_NINE_EX = "SET_NINE_EX"
const SET_TEN_EX = "SET_TEN_EX"

const SET_TWENTY_EX = "SET_TWENTY_EX"
const SET_THIRTY_EX = "SET_THIRTY_EX"
const SET_FORTY_EX = "SET_FORTY_EX"
const SET_SIXTY_EX = "SET_SIXTY_EX"

const SET_TEN_REST = "SET_TEN_REST"
const SET_FIFTEEN_REST = "SET_FIFTEEN_REST"
const SET_TWENTY_REST = "SET_TWENTY_REST"
const SET_THIRTY_REST = "SET_THIRTY_REST"

const CLEAR_BUTTON_GRID_STYLES = "CLEAR_BUTTON_GRID_STYLES"
const SET_ROUND_NUMBER_BUTTON = "SET_ROUND_NUMBER_BUTTON"
const SET_EXERCISE_NUMBER_BUTTON = "SET_EXERCISE_NUMBER_BUTTON"
const SET_REST_TIME_BUTTON = "SET_REST_TIME_BUTTON"
const SET_EXERCISE_TIME_BUTTON = "SET_EXERCISE_TIME_BUTTON"

export {
    // Params
    SET_NUMBER_OF_EXERCISES,
    SET_EXERCISE_TIME,
    SET_REST_TIME,
    SET_NUMBER_OF_ROUNDS,
    CLEAR_PARAMS,
    SET_EXERCISES,
    SET_EXERCISE_ROUNDS,
    INCLUDE_DUMBBELLS,
    EXCLUDE_DUMBBELLS,

    // Is Active
    IS_ACTIVE_TRUE,
    IS_ACTIVE_FALSE,

    // Success Gif Message
    SET_SUCCESS_GIF,

    // Selected Styles
    CLEAR_SELECTED_STYLES,

    SET_ONE_EX,
    SET_TWO_EX,
    SET_THREE_EX,
    SET_FOUR_EX,
    SET_FIVE_EX,
    SET_SIX_EX,
    SET_SEVEN_EX,
    SET_EIGHT_EX,
    SET_NINE_EX,
    SET_TEN_EX,

    SET_TWENTY_EX,
    SET_THIRTY_EX,
    SET_FORTY_EX,
    SET_SIXTY_EX,

    SET_TEN_REST,
    SET_FIFTEEN_REST,
    SET_TWENTY_REST,
    SET_THIRTY_REST,

    CLEAR_BUTTON_GRID_STYLES,
    SET_EXERCISE_NUMBER_BUTTON,
    SET_EXERCISE_TIME_BUTTON,
    SET_REST_TIME_BUTTON,
    SET_ROUND_NUMBER_BUTTON
}